services:
  - type: web
    name: payslipwexplainer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: OPENAI_API_KEY
        sync: false
